import { Router } from "express";
import customerRoutes from "./customerRoutes.js";
import favoriteRoutes from "./favoriteRoutes.js";
import menuItemsRoutes from "./menuItemsRoutes.js";
import orderItemsRoutes from "./orderItemsRoutes.js";
import otpVerificationRoutes from "./otpVerificationRoutes.js";
import paymentRoutes from "./paymentRoutes.js";
import reservationRoutes from "./reservationRoutes.js";
import restaurantTableRoutes from "./restaurantTableRoutes.js";
import restaurantsRoutes from "./restaurantsRoutes.js";
const router = Router();
router.use("/customers", customerRoutes);
router.use("/favorite", favoriteRoutes);
router.use("/menu-items", menuItemsRoutes);
router.use("/order-items", orderItemsRoutes);
router.use("/orders", orderItemsRoutes);
router.use("/otp-verification", otpVerificationRoutes);
router.use("/payment", paymentRoutes);
router.use("/reservation", reservationRoutes);
router.use("/restaurant-table", restaurantTableRoutes);
router.use("/restaurants", restaurantsRoutes);
export default router;
